### ISSUE TITLE
Suggestion: Add a test for installation success

### ISSUE THREAD

**Issue by Leedehai** [joshkel/gtpp#1]
Absolutely useful tool! I was thinking about writing my own before finding yours.
I hope there is a simple self-test script to check whether this tool is installed appropriately, due to some possible strange behaviors of Python's package management system..

**Comment by joshkel** [comment]
Thanks for the feedback, and I apologize for the delayed reply.

In general, I'd think the best test would be simply to see if the tool runs. Are there any particular problems you're concerned about?

I can see about adding a setup.py to make it a proper Python package.

**Comment by Leedehai** [comment]
No I don't have any particular problems. Thanks:)
